// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://taxtnafqrzdniadetshf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRheHRuYWZxcnpkbmlhZGV0c2hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDE5NDIsImV4cCI6MjA2Nzg3Nzk0Mn0.-5Up8BWdylMT9CyIv_Bxy7BLbjvtkp4_ScDHiO4cJSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});